sudo: false
language: node_js

node_js:
- '10'
- '12'

# keep the npm cache around to speed up installs
cache:
  directories:
  - node_modules
  - "$HOME/.npm"

before_install:
- npm update

install:
- npm ci

script:
- npm run coverage
