import { CofounderFsMethods } from '../../methods';
import cp from './cp';
import cpP from './cpP';
import glob from './glob';
import globParent from './globParent';
import globParentOf from './globParentOf';
import lstat from './lstat';
import mkdir from './mkdir';
import mkdirP from './mkdirP';
import mv from './mv';
import mvP from './mvP';
import readdir from './readdir';
import readFile from './readFile';
import rm from './rm';
import rmdir from './rmdir';
import rmdirP from './rmdirP';
import rmP from './rmP';
import writeFile from './writeFile';
import writeFileP from './writeFileP';
declare const fsMethods: CofounderFsMethods;
export { fsMethods as default, cp, cpP, glob, globParent, globParentOf, lstat, mkdir, mkdirP, mv, mvP, readdir, readFile, rm, rmdir, rmdirP, rmP, writeFile, writeFileP, };
